# Apa itu SVD
Singular Value Decomposition (SVD) adalah teknik dekomposisi matriks yang sangat berguna dalam analisis data dan pengolahan sinyal. SVD memecah matriks menjadi tiga matriks yang lebih sederhana, salah satunya matriks singular value.

$$
A = U \cdot \Sigma \cdot V^T
$$

keterangan:

$A$: Matriks asli berukuran 𝑚×𝑛.

$U$: Matriks ortogonal berukuran 𝑚×𝑚, kolom-kolomnya disebut left singular vectors.

$Σ$(Sigma): Matriks diagonal berukuran 𝑚×𝑛, berisi singular values (bilangan real ≥ 0).

$V^T$: Transpose dari matriks ortogonal
𝑉 berukuran 𝑛×𝑛, kolomnya disebut right singular vectors.

## Kegunaan SVD
Singular Value Decomposition (SVD) adalah teknik matematika yang digunakan untuk memecah matriks menjadi tiga bagian yaitu matriks singular, matriks vektor kiri, dan matriks vektor kanan. Fungsi utama dari SVD adalah untuk mengurangi dimensi data dan mempercepat proses komputasi. SVD juga digunakan dalam berbagai aplikasi seperti analisis data, pengolahan citra, dan pemrosesan sinyal.
## Bagaimana formula SVD
bentuk formula umunya:

Jika $𝐴$ adalah $𝑚×𝑛$, maka:

$$
A = U \Sigma V^T =
\begin{bmatrix}
\,|\, & \,|\, &        & \,|\, \\
u_1 & u_2 & \cdots & u_m \\
\,|\, & \,|\, &        & \,|\, \\
\end{bmatrix}
\begin{bmatrix}
\sigma_1 & 0        & \cdots & 0 \\
0        & \sigma_2 & \cdots & 0 \\
\vdots   & \vdots   & \ddots & \vdots \\
0        & 0        & \cdots & \sigma_r \\
\end{bmatrix}
\begin{bmatrix}
- & v_1^T & - \\
- & v_2^T & - \\
  & \vdots &   \\
- & v_n^T & - \\
\end{bmatrix}
$$

In [1]:
# code pembuktian
import numpy as np

# Matriks A dari soal
A = np.array([
    [3, 7],
    [2, 5],
    [4, 3],
    [1, 1]
], dtype=float)

# Langkah 1: Hitung A^T A
A_TA = A.T @ A
print("A^T A =\n", A_TA)

# Langkah 2: Hitung eigenvalue dan eigenvector A^T A
eigvals, eigvecs = np.linalg.eigh(A_TA)

# Urutkan dari terbesar ke terkecil
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

print("\nEigenvalues (A^T A) =", eigvals)
print("Eigenvectors (V) =\n", eigvecs)

# Langkah 3: Hitung singular value
singular_values = np.sqrt(eigvals)
print("\nSingular values =", singular_values)

# Bentuk Sigma (4x2 karena A 4x2)
Sigma = np.zeros((4, 2))
Sigma[0, 0] = singular_values[0]
Sigma[1, 1] = singular_values[1]
print("\nSigma =\n", Sigma)

# Langkah 4: Matriks V
V = eigvecs

# Langkah 5: Hitung U = (1/σ) * A * v
u1 = (A @ V[:, 0]) / singular_values[0]
u2 = (A @ V[:, 1]) / singular_values[1]

# Gabungkan jadi matriks U (4x2 untuk dua singular value)
U = np.column_stack((u1, u2))
print("\nU (2 kolom pertama) =\n", U)

# Langkah 6: Buktikan A = U Σ V^T
A_reconstructed = U @ Sigma[:2, :] @ V.T
print("\nA reconstructed =\n", A_reconstructed)

print("\nA original =\n", A)

# Hitung error rekonstruksi
error = np.linalg.norm(A - A_reconstructed)
print(f"\nReconstruction error = {error}")

A^T A =
 [[30. 44.]
 [44. 84.]]

Eigenvalues (A^T A) = [108.623638   5.376362]
Eigenvectors (V) =
 [[ 0.48835631 -0.87264432]
 [ 0.87264432  0.48835631]]

Singular values = [10.42226645  2.31869834]

Sigma =
 [[10.42226645  0.        ]
 [ 0.          2.31869834]
 [ 0.          0.        ]
 [ 0.          0.        ]]

U (2 kolom pertama) =
 [[ 0.72667296  0.34526321]
 [ 0.51235825  0.300381  ]
 [ 0.4386146  -0.87355405]
 [ 0.13058586 -0.16573437]]

A reconstructed =
 [[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

A original =
 [[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

Reconstruction error = 1.88411095042053e-15
